before:
  hooks:
    - make setup
    - go generate ./...
project_name: webter
release:
  github:
    owner: maddygoround
    name: webter
builds:
  - id: webter-darwin-amd64
    ldflags:
      - -s -w -X github.com/maddygoround/webter/pkg/version.Version={{.Version}}
    binary: webter
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: webter-linux-amd64
    ldflags:
      - -s -w -X github.com/maddygoround/webter/pkg/version.Version={{.Version}}
    binary: webter
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: webter-windows-amd64
    ldflags:
      - -s -w -X github.com/maddygoround/webter/pkg/version.Version={{.Version}}
    binary: webter
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
      
checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"